export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const CHANGE_DIALOG_BUT_TEXT = 'CHANGE_DIALOG_BUT_TEXT';
export const CHANGE_DIALOG_REDUCER = 'CHANGE_DIALOG_REDUCER';
