/////////////////MIDDELWARE
export const SERVER_REQUEST_SEND = 'SERVER_REQUEST_SEND';
export const SERVER_REQUEST_SUCCEEDED = 'SERVER_REQUEST_SUCCEEDED';
export const SERVER_REQUEST_ERROR = 'SERVER_REQUEST_ERROR';
export const LABEL_SEND = 'LABEL_SEND';
export const LABEL_SUCCEEDED = 'LABEL_SUCCEEDED';
export const LABEL_ERROR = 'LABEL_ERROR';
/////////////////MIDDELWARE UNTILL HERE