//new types  succeeded
export const LOGIN_USER_NAME_CHANGED = 'LOGIN_USER_NAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const LOGIN_VALIDATION_ERROR = 'LOGIN_VALIDATION_ERROR';



export const LOGIN_CREDENTIAL_ERROR = 'LOGIN_CREDENTIAL_ERROR';
export const LOGIN_USER_LOCKED = 'LOGIN_USER_LOCKED';
export const LOGIN_NEED_CHANGE_PASSWORD = 'LOGIN_NEED_CHANGE_PASSWORD';
export const LOGIN_INIT_ERROR = 'LOGIN_INIT_ERROR';

// Forgot password
export const FORGOT_PASSWORD_CLICKED = 'FORGOT_PASSWORD_CLICKED';
export const FORGOT_PASSWORD_EMAIL_CHANGED = 'FORGOT_PASSWORD_EMAIL_CHANGED';
export const FORGOT_PASSWORD_BACK_TO_LOGIN = 'FORGOT_PASSWORD_BACK_TO_LOGIN';

export const FORGOT_PASSWORD_VALIDATION_ERROR = 'FORGOT_PASSWORD_VALIDATION_ERROR';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_INIT_ERROR = 'FORGOT_PASSWORD_INIT_ERROR';

// change password
export const CHANGE_PASSWORD_MEW_CHANGED = 'CHANGE_PASSWORD_MEW_CHANGED';
export const CHANGE_PASSWORD_CONFIRM_CHANGED = 'CHANGE_PASSWORD_CONFIRM_CHANGED';
export const CHANGE_PASSWORD_VALIDATION_ERROR = 'CHANGE_PASSWORD_VALIDATION_ERROR';
export const CHANGE_PASSWORD_PASSWORD_USED = 'CHANGE_PASSWORD_PASSWORD_USED';
export const CHANGE_PASSWORD_ID_UNEXIST = 'CHANGE_PASSWORD_ID_UNEXIST';
export const CHANGE_PASSWORD_INIT_ERROR = 'CHANGE_PASSWORD_INIT_ERROR';

// common types
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

/////////////////MIDDELWARE
export const SERVER_REQUEST_SEND = 'SERVER_REQUEST_SEND';
export const SERVER_REQUEST_SUCCEEDED = 'SERVER_REQUEST_SUCCEEDED';
export const SERVER_REQUEST_ERROR = 'SERVER_REQUEST_ERROR';
/////////////////MIDDELWARE UNTILL HERE