// LOGIN ERRORS
export const USER_LOCKED = 'USER_LOCKED';
export const NEED_CHANGE_PASSWORD = 'NEED_CHANGE_PASSWORD';
export const CREDENTIAL_ERROR = 'CREDENTIAL_ERROR';
export const USER_ID__NOT_EXIST = 'USER_ID__NOT_EXIST';
export const PASSWORD_USED = 'PASSWORD_USED';
export const GENERAL_ERROR = 'GENERAL_ERROR';
// FORGOT PASSWORD ERROR
