export const HOME_CLICK = 'HOME_CLICK';
export const ALERT_CLICK = 'ALERT_CLICK';
export const PATIENT_CLICK = 'PATIENT_CLICK';
export const MESSAGE_CLICK = 'MESSAGE_CLICK';
export const CARE_PLAN_CLICK = 'CARE_PLAN_CLICK';
export const CHANGE_LAYOUT_SECTION = 'CHANGE_LAYOUT_SECTION';

export const SHOW_CARD = 'SHOW_CARD';
export const HIDE_CARD = 'HIDE_CARD';
export const SHOW_CARD_DETAILS = 'SHOW_CARD_DETAILS';
export const HIDE_CARD_DETAILS = 'HIDE_CARD_DETAILS';