export const CM_CALL_PATIENT = 'CM_CALL_PATIENT';
export const CM_DECLINE = 'CM_DECLINE';
export const PATIENT_DECLINE = 'PATIENT_DECLINE';
export const PATIENT_ANSWER_VIDEO = 'PATIENT_ANSWER_VIDEO';
export const CM_HUNG_UP = 'CM_CALL_HUNG_UP';
export const PATIENT_HUNG_UP = 'PATIENT_HUNG_UP';
